branches:
  only:
  - develop
  - master
language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - node_modules
install:
  # `awscli` is required for invalidation of CloudFront distributions.
  - pip install --user awscli
  - yarn install

jobs:
  include:
    - stage: test
      script: ".travis/run_tests.sh"
    - stage: deploy
      script: ".travis/run_build_and_deploy.sh"
stages:
  - test
  - name: deploy
    if: (branch = develop) AND (NOT (type IN (push, pull_request)))

# script:
#   - yarn test
#   - yarn build
#   - cd build/
#   - aws s3 sync . "s3://bmacfarlane-website" --delete
