branches:
  only:
  - develop
  - master
language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - node_modules
install:
  # `awscli` is required for invalidation of CloudFront distributions.
  - pip install --user awscli
  - yarn install
script:
  - yarn test
  - yarn build
  - cd build/
  - aws s3 sync . "s3://bmacfarlane-website" --delete
