#!/bin/bash
echo ">>>> In run_tests.sh"
echo "INFO: TRAVIS_BRANCH($TRAVIS_BRANCH) TRAVIS_PULL_REQUEST($TRAVIS_PULL_REQUEST) TRAVIS_PULL_REQUEST_BRANCH($TRAVIS_PULL_REQUEST_BRANCH) TRAVIS_TAG($TRAVIS_TAG)"

yarn test
